# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = lib.mkForce [ ]; # override default Jovian initrd kernel modules as they needlessly load amdgpu and make unl0kr disappear
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8d928f4c-03e1-4678-ac55-98e0a4f5b1a8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8d928f4c-03e1-4678-ac55-98e0a4f5b1a8".device = "/dev/disk/by-uuid/8d928f4c-03e1-4678-ac55-98e0a4f5b1a8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/109A-9789";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
